FROM amazonlinux:1

LABEL maintainer="ntade@rei.com"

RUN yum upgrade -q -y && yum install -q -y \
    git autoconf automake gcc zlib-devel libuuid-devel bzip2 rpm-build libtool check check-devel scons \
    rpm-build redhat-rpm-config yum-utils curl libmnl-devel make pkgconfig zlib-devel

RUN groupadd -g 1000 rpmbuilder && useradd -g rpmbuilder -u 1000 rpmbuilder

WORKDIR /home/rpmbuilder

COPY config/*.sh ./

RUN chown rpmbuilder *.sh 

USER rpmbuilder

RUN echo "%_topdir    %{getenv:HOME}/rpmbuild" > ~/.rpmmacros && mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
